module.exports = {
	root: true,
	env: {
		node: true,
	},
	parser: "@typescript-eslint/parser",
	rules: {
		semi: ["error", "always", { omitLastInOneLineBlock: true }],
		"no-multiple-empty-lines": ["error", { max: 2, maxEOF: 0, maxBOF: 0 }],
		quotes: ["error", "double", { avoidEscape: true }],
		camelcase: ["error", { properties: "never", ignoreDestructuring: true }],
		curly: ["error", "multi-or-nest"],
		eqeqeq: ["error", "always", { null: "ignore" }],
		"one-var": ["error", "consecutive"],
		"linebreak-style": ["error", "unix"],
		"prefer-const": "error",
		"no-multi-spaces": "error",
		"object-shorthand": "error",
		"quote-props": ["error", "as-needed"],
		"prefer-destructuring": [
			"error",
			{
				object: true,
				array: false,
			},
		],
		"prefer-template": "error",
		"space-before-blocks": ["error", "always"],
		"space-infix-ops": "error",
		"func-call-spacing": ["error", "never"],
		"key-spacing": ["error", { beforeColon: false }],
		"dot-notation": "error",
		"no-case-declarations": "error",
		"brace-style": "error",
		"template-curly-spacing": "error",
		"no-console": "warn",
		"no-var": "error",
		"@typescript-eslint/no-explicit-any": "error",
		"no-eval": "warn",
		"no-undefined": "error",
		"no-eq-null": "error",
		"@typescript-eslint/array-type": ["error", { default: "array" }],
		"no-lonely-if": "error",
		"arrow-body-style": "off",
		"prefer-arrow-callback": "off",
		radix: "off",
		"no-empty": ["error", { allowEmptyCatch: true }],
		"unicorn/consistent-destructuring": "error",
		"unicorn/empty-brace-spaces": "error",
		"unicorn/no-array-for-each": "error",
		"unicorn/no-empty-file": "error",
		"unicorn/no-for-loop": "error",
		"unicorn/no-instanceof-array": "error",
		"unicorn/no-lonely-if": "error",
		"unicorn/prefer-array-find": "error",
		"unicorn/prefer-array-flat": "error",
		"unicorn/prefer-array-flat-map": "error",
		"unicorn/prefer-array-index-of": "error",
		"unicorn/prefer-date-now": "error",
		"unicorn/prefer-default-parameters": "error",
		"unicorn/prefer-includes": "error",
		"unicorn/prefer-string-replace-all": "error",
		"unicorn/prefer-string-starts-ends-with": "error",
		"unicorn/prefer-string-trim-start-end": "error",
		"unicorn/prefer-switch": "error",
		"unicorn/require-number-to-fixed-digits-argument": "error",
		"unicorn/throw-new-error": "error",
		"unicorn/no-unreadable-array-destructuring": "error",
		"unicorn/prefer-logical-operator-over-ternary": "error",
		"simple-import-sort/imports": "error",
		"simple-import-sort/exports": "error",
		"unused-imports/no-unused-imports": "error",
		"unused-imports/no-unused-vars": ["warn", { vars: "all", varsIgnorePattern: "^_", args: "after-used", argsIgnorePattern: "^_" }],
	},
	plugins: ["@typescript-eslint", "unicorn", "simple-import-sort", "unused-imports"],
	extends: ["eslint:recommended", "plugin:@typescript-eslint/eslint-recommended", "plugin:@typescript-eslint/recommended", "prettier"],
};
