name: Lint & Test Package
on: ['push']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          registry-url: "https://npm.pkg.github.com"

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm run lint:ci

      - name: Run tests
        run: pnpm run test:ci
